package br.com.frameroom.view;


import br.com.frameroom.dao.UsuariosDAO;
import br.com.frameroom.model.Usuarios;
import br.com.frameroom.model.Utilitarios;
import java.security.MessageDigest;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Rodrigo
 */
public class Login extends javax.swing.JFrame {



    /**
     * Creates new form NewSignin
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
     
        
        jPanel6.setVisible(false);
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carregamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }
    
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtemail = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        btnRegistro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel_SoftZyd1 = new javax.swing.JLabel();
        jLabel_inven1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel_SoftZyd = new javax.swing.JLabel();
        jLabel_inven = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        selectCargo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(22, 25, 29));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(22, 25, 29));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemail.setBackground(new java.awt.Color(31, 36, 42));
        txtemail.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        txtemail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtemailMouseMoved(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 205, 260, 40));

        txtsenha.setBackground(new java.awt.Color(31, 36, 42));
        txtsenha.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtsenha.setForeground(new java.awt.Color(255, 255, 255));
        txtsenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 305, 260, 40));

        btnRegistro.setBackground(new java.awt.Color(169, 224, 49));
        btnRegistro.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("Registre-se");
        btnRegistro.setBorder(null);
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.setRequestFocusEnabled(false);
        btnRegistro.setVerifyInputWhenFocusTarget(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_User_Shield_100px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Lock_35px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 45));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(200, 33, 16));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Male_User_35px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 45));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("E-mail");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 80, -1));

        jLabel_SoftZyd1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_SoftZyd1.setForeground(new java.awt.Color(192, 27, 54));
        jLabel_SoftZyd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unimontes-logo-400px.png"))); // NOI18N
        jLabel_SoftZyd1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel_SoftZyd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 420, -1));
        jLabel_SoftZyd1.setVisible(false);

        jLabel_inven1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_inven1.setForeground(new java.awt.Color(48, 71, 125));
        jLabel_inven1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/frameroom-text-2.png"))); // NOI18N
        jPanel1.add(jLabel_inven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 360, 420, 180));
        jLabel_inven1.setVisible(false);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 40, 40));

        jLabel_SoftZyd.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_SoftZyd.setForeground(new java.awt.Color(192, 27, 54));
        jLabel_SoftZyd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unimontes-logo-400px.png"))); // NOI18N
        jLabel_SoftZyd.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel_SoftZyd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 410, -1));

        jLabel_inven.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_inven.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_inven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/frameroom-text-2.png"))); // NOI18N
        jPanel3.add(jLabel_inven, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 380, 440, 140));

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectCargo.setBackground(new java.awt.Color(31, 36, 42));
        selectCargo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        selectCargo.setForeground(new java.awt.Color(255, 255, 255));
        selectCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnico", "Docente CCET", "Discente CCET", "Dicente", "Docente", "Outros" }));
        selectCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        selectCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selectCargo.setFocusable(false);
        selectCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCargoActionPerformed(evt);
            }
        });
        jPanel6.add(selectCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 380, 120, 30));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tipo de usuário");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 140, 40));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nome completo");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 50));

        txtNome.setBackground(new java.awt.Color(31, 36, 42));
        txtNome.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        txtNome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtNomeMouseMoved(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel6.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 150, 40));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("E-mail");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 60, 40));

        txtEmail.setBackground(new java.awt.Color(31, 36, 42));
        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        txtEmail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtEmailMouseMoved(evt);
            }
        });
        jPanel6.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, 40));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Senha");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 249, 60, 60));

        txtSenha.setBackground(new java.awt.Color(31, 36, 42));
        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        jPanel6.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 292, 150, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(200, 33, 16));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-register.png"))); // NOI18N
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 120, 90));

        jButton14.setBackground(new java.awt.Color(200, 33, 16));
        jButton14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_To_25px.png"))); // NOI18N
        jButton14.setText("Voltar");
        jButton14.setBorder(null);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setRequestFocusEnabled(false);
        jButton14.setVerifyInputWhenFocusTarget(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 505, 110, 30));

        btnRegistrar.setBackground(new java.awt.Color(66, 68, 153));
        btnRegistrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel6.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 330, 40));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CPF");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 140, 40));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Telefone");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 140, 40));

        txtConfirmarSenha.setBackground(new java.awt.Color(31, 36, 42));
        txtConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtConfirmarSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmarSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        jPanel6.add(txtConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 292, 160, 40));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Confirme sua senha");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 249, 170, 60));

        txtCpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        jPanel6.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 160, 40));
        txtCpf.setBackground(new java.awt.Color(31, 36, 42));

        txtCpf.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        txtCpf.setForeground(new java.awt.Color(255, 255, 255));

        txtTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 68, 153)));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel6.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, 40));
        txtTelefone.setBackground(new java.awt.Color(31, 36, 42));

        txtTelefone.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 560));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 450, 620));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Senha");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, -1));

        btnEntrar.setBackground(new java.awt.Color(66, 68, 153));
        btnEntrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setFocusPainted(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseMoved

    }//GEN-LAST:event_txtemailMouseMoved

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
                jLabel_SoftZyd.setVisible(false);
                jLabel_inven.setVisible(false);
                jPanel6.setVisible(true);
                
                jLabel_SoftZyd1.setVisible(true);
                jLabel_inven1.setVisible(true);
                
                txtemail.setVisible(false);
                txtsenha.setVisible(false);
                btnRegistro.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jLabel19.setVisible(false);
                jLabel20.setVisible(false);
                btnEntrar.setVisible(false);

                
                
              
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
        
        try {
            
            if(txtCpf.getText().isEmpty() ||  txtemail.getText().isEmpty() || txtsenha.getText().isEmpty()){

                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            }
            
            else{
            String email, senha;
                        
            // Criptografia de senha
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte messageDigest[] = md.digest(txtsenha.getText().getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder();
                
            for(byte b : messageDigest){
              sb.append(String.format("%02X", 0xFF & b));
            }
                
            String senhaHex = sb.toString();
                           
            email = txtemail.getText();
            senha = senhaHex;
            
            UsuariosDAO dao = new UsuariosDAO();
            
            dao.efetuaLogin(email, senha);
            
            this.dispose();

            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e);
            
        }
    
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // botao registrar

        try {
            Usuarios obj = new Usuarios();
            UsuariosDAO dao = new UsuariosDAO();

            //Verificando se todos os campos estao preenchidos
            if(txtCpf.getText().isEmpty() ||  txtNome.getText().isEmpty() || txtTelefone.getText().isEmpty() || txtEmail.getText().isEmpty() || txtSenha.getText().isEmpty() || txtConfirmarSenha.getText().isEmpty() ){

                JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
            }

            // Verificando se as senha coincidem
            else if(!(txtSenha.getText().equals(txtConfirmarSenha.getText()))){
                JOptionPane.showMessageDialog(null, "As senhas devem ser iguais!");
            }

            // Verificando se email ja existe no bd
            else if(dao.verificaEmail(txtEmail.getText())){
                JOptionPane.showMessageDialog(null, "Email ja existe!");
            }
            
             else if(dao.verificaCpf(txtCpf.getText())){
                JOptionPane.showMessageDialog(null, "Cpf ja existe!");
            }

            // Cadastra no banco
            else{

                // Criptografia de senha
                MessageDigest md = MessageDigest.getInstance("MD5");
                byte messageDigest[] = md.digest(txtSenha.getText().getBytes("UTF-8"));
                StringBuilder sb = new StringBuilder();

                for(byte b : messageDigest){
                    sb.append(String.format("%02X", 0xFF & b));

                }

                String senhaHex = sb.toString();

                // Salvando dados
                obj.setCpf(txtCpf.getText());
                obj.setNome(txtNome.getText());
                obj.setTelefone(txtTelefone.getText());
                obj.setEmail(txtEmail.getText());
                obj.setSenha(senhaHex);
                obj.setCod_cargo(selectCargo.getSelectedIndex());

                dao.cadastrarUsuario(obj);

                new Utilitarios().LimpaTela(jPanel6);
                jPanel6.setVisible(false);
                jLabel_SoftZyd.setVisible(true);
                jLabel_inven.setVisible(true);
                
                txtemail.setVisible(true);
                txtsenha.setVisible(true);
                btnRegistro.setVisible(true);
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jLabel4.setVisible(true);
                jLabel19.setVisible(true);
                jLabel20.setVisible(true);
                btnEntrar.setVisible(true);
                
                jLabel_SoftZyd1.setVisible(false);
                jLabel_inven1.setVisible(false);
            }

            // A fazer: verificar se email/cpf/telefone é valido

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jPanel6.setVisible(false);
        jLabel_SoftZyd.setVisible(true);
        jLabel_inven.setVisible(true);
        
                txtemail.setVisible(true);
                txtsenha.setVisible(true);
                btnRegistro.setVisible(true);
                jLabel2.setVisible(true);
                jLabel3.setVisible(true);
                jLabel4.setVisible(true);
                jLabel19.setVisible(true);
                jLabel20.setVisible(true);
                btnEntrar.setVisible(true);
                
                jLabel_SoftZyd1.setVisible(false);
                jLabel_inven1.setVisible(false);

    }//GEN-LAST:event_jButton14ActionPerformed

    private void txtEmailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMouseMoved

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMouseMoved

    private void selectCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
        UIManager.put("TextField.caretForeground", new java.awt.Color(255, 255, 255));
        UIManager.put("PasswordField.caretForeground", new java.awt.Color(255, 255, 255));
        UIManager.put("FormattedTextField.caretForeground", new java.awt.Color(255, 255, 255));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_SoftZyd;
    private javax.swing.JLabel jLabel_SoftZyd1;
    private javax.swing.JLabel jLabel_inven;
    private javax.swing.JLabel jLabel_inven1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> selectCargo;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
